Resources:
  PrimaryEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0abcdef1234567890  # Replace with valid AMI ID
      KeyName: my-key-pair
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  BackupS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: disaster-recovery-backups

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
